config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "foods#index"

  resources :foods, only: [:index, :new, :create, :destroy]
  resources :public_recipes, only: [:index]

  resources :recipes, only: [:index, :new, :create, :destroy, :show, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy]
    resources :general_shopping_lists, only: [:index]
  end
  resources :inventories, only: [:index, :new, :create, :destroy, :show] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end
  
  devise_scope  :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  # Defines the root path route ("/")
  # root "articles#index"
  # resources :foods, only: [:index, :create, :new, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods, dependent: :destroy
  has_many :inventory_foods
  has_many :inventories, through: :inventory_foods, dependent: :destroy

  validates :name, presence: true
  validates :measurementUnit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
  has_many :foods, through: :inventory_foods

  validates :name, presence: true
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :food
  belongs_to :inventory
end

app/models/public_recipe.rb
class PublicRecipe < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :description, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  has_many :recipes
  has_many :inventories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_up_path_for(_resource)
    root_path
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods
  end

  def new
    @user = current_user
    @food = Food.new
  end

  def create
    @food = current_user.foods.create(food_params)
    if @food.save
      flash[:success] = 'Food created succesfully'
      redirect_to foods_url
    else
      render 'new'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    flash[:success] = 'Food deleted successfully'
    redirect_to root_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurementUnit, :price, :user_id)
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @inventories = current_user.inventories
  end

  def new
    @user = current_user
    @inventory = Inventory.new
  end

  def show
    @inventory = Inventory.find(params[:id])
    @foods = InventoryFood.all
  end

  def create
    @inventory = current_user.inventories.new(inventory_params)
    if @inventory.save
      flash[:success] = 'Inventory created succesfully'
      redirect_to inventories_url
    else
      render 'new'
    end
  end

  def destroy
    @inventory = Inventory.find_by(id: params[:id])
    @inventory.destroy
    flash[:success] = 'Inventory deleted successfully'
    redirect_to inventories_url
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes
  end

  def new
    @user = current_user
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
    @foods = RecipeFood.all
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      flash[:success] = 'Recipe created succesfully'
      redirect_to recipes_url
    else
      render 'new'
    end
  end

  def destroy
    @recipe = Recipe.find_by(id: params[:id])
    @recipe.destroy
    flash[:success] = 'Recipe deleted successfully'
    redirect_to recipes_url
  end

  def update
    @recipe = Recipe.find_by(id: params[:id])
    @recipe.update_attribute(:public, true)
    redirect_to recipes_url
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparationTime, :cookingTime, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/generate_recipe_helper.rb
module GenerateRecipeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<h1> Foods </h1>
  <div>
  <div>
  </div>
        <div > <%= link_to 'New food', new_food_path %></div> 

        <table class="table">
        <thead>
            <tr>
            <th >Food</th>
            <th >Measurement Unit</th>
            <th >Price</th>
            <th >Actions</th>
            </tr>
        </thead>

        <tbody>
        <% current_user.foods.each do |food| %>
            <tr>
            <td><%= food.name %></td>
            <td><%= food.measurementUnit %></td>
            <td><%= food.price %></td>
            <td><%= button_to "Delete Food", food_path(food.id), method: :delete, 
                    data: {confirm: 'Are you sure?'}, class: "btn btn-primary" %> </td>
            
            </tr>
            <% end %>
        </tbody>


        </table>

    </div>

app/views/foods/new.html.erb
<h1 class='text-center mb-3'>New Food</h1>

<div class='mb-5'>
  <%= form_with(model: @food, url: foods_path) do |f| %>

      <div class="row form ml-4">
    <div class= "form-group d-flex mb-4" >
      <%= f.label "Name:", class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-7" >
      <%= f.text_field :name,   class:"form-control", placeholder: "Enter food name", autofocus: true %>
      </div>
    </div>

    <div class= "form-group d-flex" >
      <%= f.label "Measurement Unit:", class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-7" >
      <%= f.text_field :measurementUnit, class:"form-control", placeholder: "Enter measurement unit (e.g: kg, l, unit", autofocus: true %>
      </div>
    </div>


    <div class= "form-group d-flex my-4" >
      <%= f.label "Price (USD):", class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-2" >
      <%= f.number_field :price, step: :any, class:"form-control", autofocus: true %>
      </div>
    </div>
    
    <div class= "form-group d-flex" >
      <div class= "col-sm-2  mx-4"></div>
      <%= f.submit class: "btn btn-lg btn-warning submit-btn mt-4" %>
    </div>
  </div>
  
  
  
  <% end %>
</div>

app/views/inventories/index.html.erb
<div>
<h1>Inventory List</h1>

<div > <%= link_to 'New Inventory', new_inventory_path %></div>

  <% current_user.inventories.each do |inv| %>
    <div>
    <%= link_to 'See inventory', inventory_path(inv.id) %>
    <h2><%= inv.name %></h2>
    <%= button_to "Delete Inventory", inventory_path(inv.id), method: :delete, 
      data: {confirm: 'Are you sure?'}, class: "btn btn-primary" %>
    </div>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

    <% end %>
</div>

app/views/inventories/new.html.erb
<h1 class='text-center mb-3'>New Inventory</h1>

<div class='mb-5'>
  <%= form_with(model: @inventory, url: inventories_path) do |f| %>

      <div class="row form ml-4">
    <div class= "form-group d-flex mb-4" >
      <%= f.label "Name:", class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-7" >
      <%= f.text_field :name,   class:"form-control", placeholder: "Enter food name", autofocus: true %>
      </div>
    </div>
    
    <div class= "form-group d-flex" >
      <div class= "col-sm-2  mx-4"></div>
      <%= f.submit class: "btn btn-lg btn-warning submit-btn mt-4" %>
    </div>
  </div> 
  
  <% end %>
</div>

app/views/inventories/show.html.erb
<div>
  <h1><%= @inventory.name %></h1>
  <div > <%= link_to 'Add food', new_inventory_inventory_food_path(current_user.id) %></div>
  
 
 
  

 <table class="table">
        <thead>
            <tr>
            <th >Food</th>
            <th >Quantity</th>
            <th >Price</th>
            <th >Actions</th>
            </tr>
        </thead>

        <tbody>
        <% @foods.each do |food|%>
            <tr>
            <td><%= food.food.name %></td>
            <td><%= food.quantity %></td>
            <td><%= food.food.price %></td>
            <td><%= button_to "Delete Food", food_path(food.id), method: :delete, 
                    data: {confirm: 'Are you sure?'}, class: "btn btn-primary" %> </td>
            
            </tr>
            <% end %>
        </tbody>


        </table>

</div>

app/views/recipes/index.html.erb
<div>
<h1>Recipe List</h1>

<div > <%= link_to 'New Recipe', new_recipe_path %></div>

  <% current_user.recipes.each do |recipe| %>
    <div>
    <%= link_to 'See this recipe', recipe_path(recipe.id) %>
    <h2><%= recipe.name %></h2>
    <%= button_to "Delete Recipe", recipe_path(recipe.id), method: :delete, 
      data: {confirm: 'Are you sure?'}, class: "btn btn-primary" %>
    </div>
    <p><%= recipe.description %></p>
    <% end %>
    <%= @recipe%>
</div>

app/views/recipes/new.html.erb
<h1 class='text-center mb-3'>New Recipe</h1>

<div class='mb-5'>
  <%= form_with(model: @recipe, url: recipes_path) do |f| %>

      <div class="row form ml-4">
    <div class= "form-group d-flex mb-4" >
      <%= f.label "Name:", class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-7" >
      <%= f.text_field :name,   class:"form-control", placeholder: "Enter recipe name", autofocus: true %>
      </div>
    </div>

    <div class= "form-group d-flex" >
      <%= f.label "Description:", class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-7" >
      <%= f.text_area :description, class:"form-control", placeholder: "Enter recipe description", autofocus: true %>
      </div>
    </div>


    <div class= "form-group d-flex my-4" >
      <%= f.label "Cooking time", class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-2" >
      <%= f.number_field :cookingTime,   class:"form-control", autofocus: true %>
      </div>
    </div>

    <div class= "form-group d-flex my-4" >
      <%= f.label "Preparation time", class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-2" >
      <%= f.number_field :preparationTime,   class:"form-control", autofocus: true %>
      </div>
    </div>

    <div class= "form-group d-flex my-4" >
      <%= f.label "Public", class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-2" >
      <%= f.check_box :public,   class:"form-control", autofocus: true %>
      </div>
    </div>
    
    <div class= "form-group d-flex" >
      <div class= "col-sm-2  mx-4"></div>
      <%= f.submit class: "btn btn-lg btn-warning submit-btn mt-4" %>
    </div>
  </div> 
  
  <% end %>
</div>

app/views/recipes/show.html.erb
<div>
  <h1><%= @recipe.name %></h1>
  <h3>Preparation Time: <%= @recipe.preparationTime %> hours</h3>
  <h3>Cooking Time: <%= @recipe.cookingTime %> hours</h3>  
<label class="form-check-label">Public</label>
<%= form_with url: recipe_path(@recipe), method: "put" do |form| %>
          <div class="form-check form-switch fs-5 align-self-start">
      <% if !@recipe.public %>
        <%= form.check_box :public, id: "flexSwitchCheckDefault", class: "form-check-input", onchange: "this.form.submit();" %>
        <%= form.label :public, class: "form-check-label fw-semi-bold", for: "flexSwitchCheckDefault" %>
      <% else %>
        <%= form.check_box :public, id: "flexSwitchCheckChecked", class: "form-check-input", onchange: "this.form.submit();" %>
        <%= form.label :public, class: "form-check-label fw-semi-bold", for: "flexSwitchCheckChecked" %>
      <% end %>
    </div>
  <% end %>
  <div>
    
  <div>
      <%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe), class: 'btn btn-outline-dark' %>
      <%= link_to 'Generate list', recipe_general_shopping_lists_path(@recipe) , class: 'btn btn-outline-dark' %>
 
  </div>
  
  </div>

   <table class="table">
        <thead>
            <tr>
            <th >Food</th>
            <th >Quantity</th>
            <th >Price</th>
            <th >Actions</th>
            </tr>
        </thead>

        <tbody>
        <% @foods.each do |food|%>
            <tr>
            <td><%= food.food.name %></td>
            <td><%= food.quantity %></td>
            <td><%= food.food.price %></td>
            <td><%= button_to "Delete Food", food_path(food.id), method: :delete, 
                    data: {confirm: 'Are you sure?'}, class: "btn btn-primary" %> </td>
            
            </tr>
            <% end %>
        </tbody>


        </table>

</div>